### ISSUE TITLE
Chat service feature request

### ISSUE THREAD

**Issue by crutchcorn** [TheAndroidMaster/TheAndroidMaster.github.io#3]
- [ ] See list of active users
- [ ] Google sign-in
- [ ] Only one person to have the same name (no multiple "Corbin"s)
- [ ] Emojis
- [x] /nick command to change nicknames
- [x] /color command to change text color
- [x] Notification sounds/Title text change/Chrome & Firefox APIs
- [x] Specify the chatroom in the url
- [ ] Move help from separate page to a dialog

**Comment by TheAndroidMaster** [comment]
Most of these can be put into two categories: ip address and markdown

The markdown will take a while to make, but is fairly easy to do, all I need to do is replace html-specific characters with ones from a stackoverflow question which I put a link to on the chat... which then conveniently deleted itself moments later.

The ip address... will take a little longer. Getting the ip is really easy, but I will need to change... just about everything about how the chat works first.

**Comment by TheAndroidMaster** [comment]
Instead of a /nick command I added a menu button with the option inside it. I will probably add more options to the menu later, like maybe a help section and/or emoji panel.

**Comment by crutchcorn** [comment]
Add the emoji panel inside of the input (or at lease next to it). Also, the notifications need work and integrations with the web standard API.

**Comment by TheAndroidMaster** [comment]
I think the help section will work fine as a separate page, but I will get it to open in a new tab instead of the same window. Also, top bar tabs and lists of active users will be very hard to implement, I think we should wait until later to implement those. 

Also, I just implemented notification sounds, so the notification feature should be finished. I might have it make the title "blink" until the user tabs back onto the page, though.

**Comment by crutchcorn** [comment]
Help should be a dialog. From the UX sense it makes no sense to have it be a different page...
Just because something is hard doesn't mean we should hold off on it. ;) 

I know you implemented it, but it needs a LOT of work. It flashes once and that's it, doesn't use the API for it, and more

**Comment by TheAndroidMaster** [comment]
I'll just leave it for later. there are other things I want to do, like remaking the entire php file to prevent one very annoying bug...

**Comment by crutchcorn** [comment]
Gotcha

**Comment by TheAndroidMaster** [comment]
The title now blinks and there is a notification sound. Also there are different colors based on the user, so you can tell people with the same name apart. And it shows the enter/exit message when switching chatrooms as well as just opening/closing the tab. I also made it change the url based on the current chatroom, so you can give people links to specific rooms instead of just "log".

**Comment by TheAndroidMaster** [comment]
Chatroom doesn't exist anymore. Closing issue :P
